### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davidnewhall** [Unpackerr/xt#3]
- [x] man page
- [x] use pflag
- [ ] better help menu
- [x] expose all the xtractr options as flags
- [x] optional file system recursion.
- [ ] optional archive recursion.
- [ ] sign Mac app
- [ ] windows installer?
- [ ] sign windows installer?
- [x] update readme with installation instructions
- [ ] [update website](https://github.com/Unpackerr/unpackerr.github.io/blob/main/docs/xt.md) with more info about usage options.
- [ ] custom icon
